version: '3.9'

services:
  frametv:
    image: ghcr.io/mrtncode/frametv-art-gallery:latest
    container_name: frametv_artgallery
    ports:
      - "8000:8000"
    volumes:
      - frametv_data:/data
    environment:
      - SECRET_KEY=supersecretkey
      - FRAME_TV_DATA=/data

volumes:
  frametv_data: