"""Add delete_other_images_on_upload to TV

Revision ID: 500fac4679d4
Revises: a16beaf2617d
Create Date: 2026-02-23 17:52:45.998022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500fac4679d4'
down_revision = 'a16beaf2617d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_other_images_on_upload', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv', schema=None) as batch_op:
        batch_op.drop_column('delete_other_images_on_upload')

    # ### end Alembic commands ###
