"""empty message

Revision ID: 601a7cee3cbb
Revises: 500fac4679d4
Create Date: 2026-03-11 11:32:22.588128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601a7cee3cbb'
down_revision = '500fac4679d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # the previous foreign key was anonymous in SQLite; recreate it with a
    # proper name and ON DELETE CASCADE. drop the old one when the dialect
    # supports named constraints (i.e. not sqlite).
    fk_name = 'fk_uploaded_image_tv_id'
    bind = op.get_bind()
    dialect = bind.dialect.name
    with op.batch_alter_table('uploaded_image', schema=None) as batch_op:
        if dialect != 'sqlite':
            # non-sqlite databases can drop the existing named constraint
            batch_op.drop_constraint(fk_name, type_='foreignkey')
        batch_op.create_foreign_key(fk_name, 'tv', ['tv_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    fk_name = 'fk_uploaded_image_tv_id'
    bind = op.get_bind()
    dialect = bind.dialect.name
    with op.batch_alter_table('uploaded_image', schema=None) as batch_op:
        if dialect != 'sqlite':
            batch_op.drop_constraint(fk_name, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tv', ['tv_id'], ['id'])

    # ### end Alembic commands ###
