"""Add created_at to Album

Revision ID: 929a60c602a1
Revises: 
Create Date: 2026-02-21 16:03:42.932128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929a60c602a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
