"""make created_at nullable

Revision ID: a16beaf2617d
Revises: 929a60c602a1
Create Date: 2026-02-21 16:37:37.622413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16beaf2617d'
down_revision = '929a60c602a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.alter_column('album_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
