"""Add app settings table for github cache

Revision ID: ce4757b9dde8
Revises: f2a4d1c9e8b7
Create Date: 2026-08-30 16:51:16.946701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4757b9dde8'
down_revision = 'f2a4d1c9e8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tv_slideshow_album_id_album', 'album', ['slideshow_album_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tv', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tv_slideshow_album_id_album', type_='foreignkey')

    # ### end Alembic commands ###
